### ISSUE TITLE
Guide "Access a database with Micronaut Data JDBC" fails to generate native executable

### ISSUE THREAD

**Issue by nenadvico** [micronaut-projects/micronaut-guides#1051]
Guide "Access a database with Micronaut Data JDBC" [https://guides.micronaut.io/latest/micronaut-data-jdbc-repository-gradle-java.html](url) fails to generate native executable at step 8.1
After running
`./gradlew nativeCompile
`
I got next:

```

[native-image-plugin] Using executable path: /Users/nenadvico/.sdkman/candidates/java/22.2.r11-grl/bin/native-image
Warning: Using a deprecated option --allow-incomplete-classpath from 'META-INF/native-image/io.micronaut/micronaut-inject/native-image.properties' in 'file:///Users/nenadvico/.gradle/caches/modules-2/files-2.1/io.micronaut/micronaut-inject/3.5.1/cc9e726fe97c46286e5635015d74c2b89096b790/micronaut-inject-3.5.1.jar'. Allowing an incomplete classpath is now the default. Use --link-at-build-time to report linking errors at image build time for a class or package.
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
========================================================================================================================
GraalVM Native Image: Generating 'micronautguidedb' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (12.1s @ 0.27GB)
 Version info: 'GraalVM 22.2.0 Java 11 CE'
 Java version info: '11.0.16+8-jvmci-22.2-b06'
 C compiler: cc (apple, x86_64, 13.1.6)
 Garbage collector: Serial GC
 6 user-specific feature(s)
 - io.micronaut.buffer.netty.NettyFeature
 - io.micronaut.core.graal.ServiceLoaderFeature
 - io.micronaut.flyway.graalvm.FlywayFeature
 - io.micronaut.http.netty.graal.HttpNettyFeature
 - io.micronaut.jackson.JacksonDatabindFeature
 - io.micronaut.jdbc.nativeimage.JdbcFeature

Fatal error: java.lang.IllegalAccessError: class io.micronaut.core.graal.AutomaticFeatureUtils (in unnamed module @0x252744a1) cannot access class com.oracle.svm.core.configure.ResourcesRegistry (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.configure to unnamed module @0x252744a1
        at io.micronaut.core.graal.AutomaticFeatureUtils.addResourcePatterns(AutomaticFeatureUtils.java:190)
        at io.micronaut.jdbc.nativeimage.JdbcFeature.handleMySql(JdbcFeature.java:305)
------------------------------------------------------------------------------------------------------------------------
        at io.micronaut.jdbc.nativeimage.JdbcFeature.beforeAnalysis(JdbcFeature.java:77)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:722)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:722)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
                        0.9s (6.4% of total time) in 12 GCs | Peak RSS: 0.87GB | CPU load: 2.18
========================================================================================================================
Failed generating 'micronautguidedb' after 12.2s.
Error: Image build request failed with exit status 1

> Task :nativeCompile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nativeCompile'.
> Process 'command '/Users/nenadvico/.sdkman/candidates/java/22.2.r11-grl/bin/native-image'' finished with non-zero exit value 1

```

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?
