### ISSUE TITLE
Micronaut AWS Lambda and S3 Event - Guide Example Error

### ISSUE THREAD

**Issue by mark-j-68** [micronaut-projects/micronaut-guides#1415]
Creating issue as requested in https://stackoverflow.com/questions/77781130/micronaut-aws-lambda-and-s3-event-guide-example-error.  Original content copied below;

I downloaded the example project from the "MICRONAUT AWS LAMBDA AND S3 EVENT" guide and followed the instructions to create the Lamdba, the S3 Bucket, and put a Trigger on the S3 bucket.

However, whenever I drop a jpg file into the images folder in the S3 bucket I get this error in Cloudwatch.

```
An error occurred during JSON parsing: java.lang.RuntimeException
java.lang.RuntimeException: An error occurred during JSON parsing
Caused by: io.micronaut.function.aws.CustomPojoSerializerException: io.micronaut.serde.exceptions.SerdeException: Error decoding property [List records] of type [class com.amazonaws.services.lambda.runtime.events.models.s3.S3EventNotification]: Cannot invoke "io.micronaut.serde.Deserializer.deserializeNullable(io.micronaut.serde.Decoder, io.micronaut.serde.Deserializer$DecoderContext, io.micronaut.core.type.Argument)" because "this.deserializer" is null
    at io.micronaut.function.aws.JsonMapperCustomPojoSerializer.fromJson(JsonMapperCustomPojoSerializer.java:72)
Caused by: io.micronaut.serde.exceptions.SerdeException: Error decoding property [List records] of type [class com.amazonaws.services.lambda.runtime.events.models.s3.S3EventNotification]: Cannot invoke "io.micronaut.serde.Deserializer.deserializeNullable(io.micronaut.serde.Decoder, io.micronaut.serde.Deserializer$DecoderContext, io.micronaut.core.type.Argument)" because "this.deserializer" is null
    at io.micronaut.serde.support.deserializers.DeserBean$DerProperty.deserializeAndSetConstructorValue(DeserBean.java:857)
    at io.micronaut.serde.support.deserializers.SimpleRecordLikeObjectDeserializer.deserialize(SimpleRecordLikeObjectDeserializer.java:68)
    at io.micronaut.serde.support.deserializers.SimpleRecordLikeObjectDeserializer.deserializeNullable(SimpleRecordLikeObjectDeserializer.java:102)
    at io.micronaut.serde.jackson.JacksonJsonMapper.readValue0(JacksonJsonMapper.java:177)
    at io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:169)
    at io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:206)
    at io.micronaut.function.aws.JsonMapperCustomPojoSerializer.fromJson(JsonMapperCustomPojoSerializer.java:70)
Caused by: java.lang.NullPointerException: Cannot invoke "io.micronaut.serde.Deserializer.deserializeNullable(io.micronaut.serde.Decoder, io.micronaut.serde.Deserializer$DecoderContext, io.micronaut.core.type.Argument)" because "this.deserializer" is null
    at io.micronaut.serde.support.deserializers.DeserBean$DerProperty.deserializeAndSetConstructorValue(DeserBean.java:838)

```

I had expected it to work as it's the example code from the guide and create thumbnail files.

My JAVA_HOME is set to "/home/mark/.jdks/corretto-17.0.9"

**Comment by mark-j-68** [comment]
I only just noticed this - but my issue seems to be a duplicate of https://github.com/micronaut-projects/micronaut-guides/issues/1410.

I attempted similar workarounds with similar results.
